Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-09e67e426f25ce0d7' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  NewRelicInfrastructureIntegrationsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: 11111111
            Action: 
                - "sts:AssumeRole"

      Path: '/'
      ManagedPolicyArns: 
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      RoleName: "NewRelicInfrastructureIntegrations2"
  ProfileWithRolesForOurApp: 
      Type: AWS::IAM::InstanceProfile
      Properties: 
          Path: "/"
          Roles: 
              - !Ref NewRelicInfrastructureIntegrationsRole
